application: kodekitty
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /meatball\.jpg
  static_files: meatball.jpg
  upload: meatball\.jpg
- url: /mypage_stylesheet\.css
  static_files: mypage_stylesheet.css
  upload: mypage_stylesheet\.css

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
